import { Router, type Request, type Response } from 'express';
import type { AuthRequest } from '../middleware/auth.js';
import { lgspRepository } from '../repositories/lgsp.repository.js';
import { getLgspService } from '../services/lgsp.service.js';
import { lgspSendQueue } from '../lib/queue/client.js';
import { handleDbError } from '../lib/error-handler.js';

const router = Router();

// ============================================================
// POST /gui-lien-thong — Gui van ban di qua LGSP
// Body: { outgoing_doc_id, dest_org_code, dest_org_name }
// ============================================================
router.post('/gui-lien-thong', async (req: Request, res: Response) => {
  try {
    const { staffId } = (req as AuthRequest).user;
    const { outgoing_doc_id, dest_org_code, dest_org_name } = req.body;

    if (!outgoing_doc_id) {
      res.status(400).json({ success: false, message: 'outgoing_doc_id la bat buoc' });
      return;
    }
    if (!dest_org_code) {
      res.status(400).json({ success: false, message: 'dest_org_code la bat buoc' });
      return;
    }

    // Create tracking record with status 'pending'
    const tracking = await lgspRepository.createTracking(
      Number(outgoing_doc_id),
      'send',
      dest_org_code,
      dest_org_name || null,
      null, // edxml_content — generated by worker
      staffId,
    );

    if (!tracking.success) {
      res.status(400).json({ success: false, message: tracking.message });
      return;
    }

    // Enqueue job for async LGSP send
    await lgspSendQueue.add('send-doc', {
      tracking_id: tracking.id,
      outgoing_doc_id: Number(outgoing_doc_id),
      dest_org_code,
      dest_org_name: dest_org_name || null,
    });

    res.status(201).json({
      success: true,
      message: 'Da tao yeu cau gui lien thong',
      id: tracking.id,
    });
  } catch (error) {
    handleDbError(error, res);
  }
});

// ============================================================
// GET /tracking — Danh sach tracking lien thong
// Query: direction, status, page, pageSize
// ============================================================
router.get('/tracking', async (req: Request, res: Response) => {
  try {
    const { direction, status, page, pageSize } = req.query;

    const rows = await lgspRepository.getTrackingList(
      (direction as string) || null,
      (status as string) || null,
      Number(page) || 1,
      Number(pageSize) || 20,
    );

    const total = rows.length > 0 ? rows[0].total_count : 0;
    res.json({
      success: true,
      data: rows,
      pagination: {
        total,
        page: Number(page) || 1,
        pageSize: Number(pageSize) || 20,
      },
    });
  } catch (error) {
    handleDbError(error, res);
  }
});

// ============================================================
// GET /tracking/doc/:outgoingDocId — Tracking theo van ban di
// ============================================================
router.get('/tracking/doc/:outgoingDocId', async (req: Request, res: Response) => {
  try {
    const outgoingDocId = Number(req.params.outgoingDocId);
    const rows = await lgspRepository.getTrackingByDoc(outgoingDocId);
    res.json({ success: true, data: rows });
  } catch (error) {
    handleDbError(error, res);
  }
});

// ============================================================
// GET /organizations — Danh sach co quan lien thong
// Query: search, page, pageSize
// ============================================================
router.get('/organizations', async (req: Request, res: Response) => {
  try {
    const { search, page, pageSize } = req.query;

    const rows = await lgspRepository.getOrgList(
      (search as string) || null,
      Number(page) || 1,
      Number(pageSize) || 20,
    );

    const total = rows.length > 0 ? rows[0].total_count : 0;
    res.json({
      success: true,
      data: rows,
      pagination: {
        total,
        page: Number(page) || 1,
        pageSize: Number(pageSize) || 20,
      },
    });
  } catch (error) {
    handleDbError(error, res);
  }
});

// ============================================================
// POST /organizations/sync — Trigger dong bo co quan tu LGSP
// ============================================================
router.post('/organizations/sync', async (req: Request, res: Response) => {
  try {
    const service = await getLgspService();
    const orgs = await service.syncOrganizations();

    let syncedCount = 0;
    for (const org of orgs) {
      const result = await lgspRepository.syncOrg(
        org.org_code,
        org.org_name,
        org.parent_code,
        org.address,
        org.email,
        org.phone,
      );
      if (result.success) syncedCount++;
    }

    res.json({
      success: true,
      message: `Da dong bo ${syncedCount}/${orgs.length} co quan`,
      data: { total: orgs.length, synced: syncedCount },
    });
  } catch (error) {
    handleDbError(error, res);
  }
});

// ============================================================
// POST /receive-poll — Manual trigger polling LGSP (dev/debug)
// ============================================================
router.post('/receive-poll', async (req: Request, res: Response) => {
  try {
    const { staffId } = (req as AuthRequest).user;
    const service = await getLgspService();
    const docs = await service.receiveDocuments();

    const trackingIds: number[] = [];
    for (const doc of docs) {
      const result = await lgspRepository.createTracking(
        null, // incoming — no outgoing_doc_id
        'receive',
        doc.sender_org_code,
        doc.sender_org_name,
        doc.edxml_content,
        staffId,
      );
      if (result.success) {
        trackingIds.push(result.id);
        // Update status to success with lgsp_doc_id
        await lgspRepository.updateTrackingStatus(
          result.id,
          'success',
          doc.lgsp_doc_id,
          null,
        );
      }
    }

    res.json({
      success: true,
      message: `Da nhan ${docs.length} van ban tu LGSP`,
      data: { received: docs.length, tracking_ids: trackingIds },
    });
  } catch (error) {
    handleDbError(error, res);
  }
});

export default router;
